### ISSUE TITLE
The Input image of CNN would be RGB or grayscale

### ISSUE THREAD

**Issue by ashu7398** [Shuchismita-Biswas/AML_Project_Fall19#1]
can you please tell me whether the images we input in the CNN used to be RGB or grayscale after encoding and I'm also wondering when we rescale the values of the time series before between 0-1 so we can say it's grayscale as grayscale use to be between(0-255),
It would be really great help if you can clear my doubt?
Thank you

**Comment by Shuchismita-Biswas** [comment]
Hi yes you can consider the images to be grayscale and not RGB. In this
example, we are only using one channel for the CNN classification.
